/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hu.szaniszlaid.ulwila.View.notes;

import java.awt.Graphics2D;

/**
 *
 * @author Franklin
 */
public class HalfRestPanel extends NotePanel {

    
    /**
     * Creates new form HalfRestPanel
     */
    public HalfRestPanel() {
        super(new NoteBuilder()
                .setContainerWidth(180)
                .setnWidth(90));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void draw(Graphics2D g) {
        g.drawPolygon(Components.getHexagon(0, 0, getNWidth(), getNHeight()));
        g.drawPolygon(Components.getHexagon(getNWidth(), 0, getNWidth(), getNHeight()));
    }
}
