/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hu.szaniszlaid.ulwila.notes;

import java.awt.Color;
import java.awt.Graphics2D;

import hu.szaniszlaid.ulwila.note.util.Octave;

/**
 *
 * @author Franklin
 */
public class HalfNotePanel extends MusicNote {

    /**
     * Creates new form QuarterNote
     *
     * @param color
     * @param pitch
     */

    public HalfNotePanel(Color color, Octave pitch) {
        super(new NoteBuilder().setColor(color), pitch);

        setContainerWidth(getNWidth() + offsetX);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void drawNote(Graphics2D g) {
        g.setColor(getColor());
        g.fillOval(offsetX, 0, getNWidth(), getNHeight());
        g.setColor(Color.BLACK);
        g.drawOval(offsetX, 0, getNWidth(), getNHeight());
        g.setColor(getColor());
        g.fillOval(0, 0, getNWidth(), getNHeight());
        g.setColor(Color.BLACK);
        g.drawOval(0, 0, getNWidth(), getNHeight());

    }

    @Override
    public void drawOctave(Graphics2D g) {
        int centerX = getNWidth() / 2 - getNWidth() / 10;
        int centerY = getNHeight() / 2 - getNHeight() / 10;

        //belső körök
        g.fillOval(centerX, centerY, getNWidth() / 5, getNHeight() / 5);
        g.fillOval(centerX + offsetX, centerY, getNWidth() / 5, getNHeight() / 5);

        //kontúr
        g.setColor(Color.BLACK);
        g.drawOval(centerX, centerY, getNWidth() / 5, getNHeight() / 5);
        g.drawOval(centerX + offsetX, centerY, getNWidth() / 5, getNHeight() / 5);

    }
}
